# Generated by Django 3.0.1 on 2020-02-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeName', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=40)),
                ('Designation', models.CharField(choices=[('Manager', 'Manager'), ('Developer', 'Developer'), ('Tester', 'Tester'), ('HR', 'HR')], max_length=30)),
                ('Address', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
