# Generated by Django 3.0.1 on 2020-02-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRadmin', '0003_addemployee_contactno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addemployee',
            name='id',
        ),
        migrations.AddField(
            model_name='addemployee',
            name='Idno',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
