# Generated by Django 3.0.1 on 2020-02-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRadmin', '0005_auto_20200213_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addemployee',
            name='Idno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
