# Generated by Django 2.1 on 2020-03-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppicantLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Data_of_Birth', models.DateField(help_text='yyy-mm-dd')),
                ('Email_ID', models.EmailField(max_length=254)),
                ('Female', models.BooleanField(default=False, verbose_name='Male')),
                ('Mobile_No', models.IntegerField()),
                ('Address', models.CharField(max_length=50)),
                ('User_Name', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
    ]
