# Generated by Django 2.1 on 2020-03-05 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appicantlogin',
            old_name='name',
            new_name='User_name',
        ),
    ]
