# Generated by Django 2.1 on 2020-03-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_auto_20200305_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantregistration',
            name='Female',
        ),
        migrations.AddField(
            model_name='applicantregistration',
            name='Gender',
            field=models.BooleanField(default=False, verbose_name='Female'),
        ),
    ]
