# Generated by Django 2.1 on 2020-03-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0004_auto_20200306_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Data_of_Birth', models.DateField(help_text='yyy-mm-dd')),
                ('Email_ID', models.EmailField(max_length=254)),
                ('Gender', models.CharField(max_length=30)),
                ('Mobile_No', models.IntegerField()),
                ('Address', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('post', models.CharField(choices=[('developer', 'developer'), ('tester', 'tester'), ('manager', 'manager'), ('hr', 'hr')], max_length=30)),
                ('percentage', models.FloatField()),
                ('resume_upload', models.FileField(upload_to='files')),
            ],
        ),
    ]
