# Generated by Django 3.0.1 on 2020-02-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecuirtmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OPPERTUNITY_CODE', models.IntegerField()),
                ('QUALIFICATION', models.CharField(max_length=100)),
                ('REGISTRATION_START_FROM', models.DateField(help_text='yyy-mm-dd')),
                ('AGE_LIMT', models.IntegerField()),
                ('LAST_DATE_TO_APPLY', models.DateField(help_text='yyy-mm-dd')),
                ('DEPARTMENT_ID', models.IntegerField()),
                ('NO_OF_POSITION', models.IntegerField()),
                ('DESCRIPTION', models.CharField(max_length=200)),
                ('RESPOSIBITIES', models.CharField(max_length=300)),
                ('CONTACT_NO', models.IntegerField()),
            ],
        ),
    ]
