# Generated by Django 2.1 on 2020-02-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_recuirtmentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('Applicant_Id', models.IntegerField()),
                ('Sellect_emp_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Schedule_Date', models.DateField(help_text='yyy-mm-dd')),
            ],
        ),
    ]
